const fs = require("fs/promises");

const HOME_DIRECTORY = "C:\\Users\\Admin\\Desktop\\Music\\Database";

export async function fetchPlaylist(name: string) {
  //return the data (paths of music files, FOR ONE PLAYLIST) from the text file generated by the python process when first created.
  try {
    const data = await fs.readFile(
      `${HOME_DIRECTORY}\\${name}\\${name}_keys.txt`,
      "utf8"
    );
    console.log(data);
  } catch (error) {
    console.log(error);
  }
}

export async function getAllPlaylists() {
  //Return filenames of all playlists within the home directory, along with some tertiary data (no. of songs, date added maybe?)
}

export async function createPlaylist() {
  // Calls the python process that will handle the downloading, and the creation of the relevant
  // directories and textfiles
}

export async function copyPlaylist() {
  //No idea why I wrote this, as good as dead.
}



